config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  get "/me", to: "me#index", as: :me

  resources :users, only: [:show, :create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root to: "welcome#index"

  resources :belts, only: [] do
    resources :techniques, only: [:index, :show] do
      resources :notes, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      patch :give_user_next_belt
    end

    resources :techniques, only: [:index, :new, :create, :edit, :update]

    resources :belt_applications, only: [:index, :destroy] do
      member do
        post :approve
      end
    end
  end

  resources :belt_applications, only: [:new, :create]
end

app/models/belt_application.rb
class BeltApplication < ApplicationRecord
  belongs_to :user

  has_attached_file(
    :picture_proof,
    default_url: "/belt_applications/missing.png",
  )
  validates_attachment_content_type :picture_proof, content_type: /\Aimage\/.*\z/
end

app/controllers/admin/belt_applications_controller.rb
module Admin
  class BeltApplicationsController < AdminController
    def index
      @belt_applications = BeltApplication.all
    end

    def approve
      current_user.give_next_belt
      destroy_application

      redirect_to admin_belt_applications_path
    end

    def destroy
      destroy_application
      redirect_to admin_belt_applications_path
    end

    private

    def destroy_application
      BeltApplication.find(params[:id]).destroy!
    end
  end
end

app/controllers/belt_applications_controller.rb
class BeltApplicationsController < ApplicationController
  around_action :require_no_pending_applications

  def new
    @application = BeltApplication.new
  end

  def create
    application_params = params.require(:belt_application).permit(
      :picture_proof,
    )

    @application = BeltApplication.new(application_params)
    @application.user = current_user

    if @application.save
      BeltApplicationMailer.send_application_notification(current_user).deliver_now
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def require_no_pending_applications
    if current_user.belt_application.nil?
      yield
    else
      redirect_to root_path
    end
  end
end

app/views/admin/belt_applications/index.html.erb
<h1>De mennesker vil gerne opgradere deres bælter:</h1>

<% if @belt_applications.present? %>
	<div class="table-responsive">
  	<table class="table table-striped table-hover">
  	  <thead>
  	    <tr>
  	      <th>Fornavn</th>
  	      <th>Efternavn</th>
  	      <th>Bælt ansøges om</th>
  	      <th>Bevis billede</th>
  	      <th>Actions</th>
					<th></th>
  	    </tr>
  	  </thead>
  	  <tbody>
  	    <% @belt_applications.each do |belt_application| %>
  	      <tr>
  	        <td><%= belt_application.user.first_name %></td>
  	        <td><%= belt_application.user.last_name %></td>
  	        <td><%= belt_application.user.next_belt.color %></td>
  	        <td><%= link_to "Vis", belt_application.picture_proof.url, target: "_blank", class: "btn btn-default btn-xs" %></td>
  	        <td>
  	          <%= button_to "Godkende", approve_admin_belt_application_path(belt_application), method: :post, class: "btn btn-xs btn-success" %>
						</td>
  	        <td>
  	          <%= button_to "Afvise", admin_belt_application_path(belt_application), method: :delete, class: "btn btn-xs btn-danger" %>
  	        </td>
  	      </tr>
  	    <% end %>
  	  </tbody>
  	</table>
	</div>
<% else %>
  <p>Der er ingen bælte ansøgningerne endnu :(</p>
<% end %>