config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  get "/me", to: "me#index", as: :me

  resources :users, only: [:show, :create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root to: "welcome#index"

  resources :belts, only: [] do
    resources :techniques, only: [:index, :show] do
      resources :notes, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      patch :give_user_next_belt
    end

    resources :techniques, only: [:index, :new, :create, :edit, :update]

    resources :belt_applications, only: [:index, :destroy] do
      member do
        post :approve
      end
    end
  end

  resources :belt_applications, only: [:new, :create]
end

app/models/technique.rb
class Technique < ApplicationRecord
  belongs_to :belt
  has_many :notes

  validates(
    :belt,
    :name,
    :topic,
    :description,
    :long_name,
    presence: true,
  )

  enum topic: {
    sugisul: 0,
    joksul: 1,
    danjon_hohupbop: 2,
    ki_doin: 3,
    jahse: 4,
    nakbop: 5,
    su: 6,
    yaksok_daeryon: 7,
    jayu_daeryon: 8,
    hyong: 9,
    gigu_sul: 10,
    kyokpa: 11,
    tuksu_dong_jak: 12,
    hwalyong_sul: 13,
  }

  def self.search_for(query)
    like_query = "%#{query}%"

    find_by_sql([<<-SQL, like_query, like_query, like_query])
      WITH topics (topic_id, topic_name) AS (
        VALUES
          #{Technique.topics.map { |k,v| "(#{v}, '#{k.humanize}')" }.join(", ")}
      )

      SELECT *
      FROM techniques

      INNER JOIN topics
         ON topics.topic_id = techniques.topic

      WHERE techniques.name ILIKE ?
         OR techniques.description ILIKE ?
         OR topics.topic_name ILIKE ?
    SQL
  end

  def youtube_embed_url
    youtube_id = youtube_video_url.match(/[?&]v=(?<url>[^&]*)/)[:url]
    "https://www.youtube.com/embed/#{youtube_id}"
  end
end

app/controllers/admin/techniques_controller.rb
module Admin
  class TechniquesController < AdminController
    def index
      @belts = Belt.all
      @matching_techniques = if params[:query].present?
                               Technique.search_for(params[:query]).map(&:id)
                             else
                               Technique.all.pluck(:id)
                             end
    end

    def new
      @technique = Technique.new
    end

    def create
      @technique = Technique.new(
        belt: Belt.find(technique_params.fetch(:belt_id)),
        name: technique_params.fetch(:name),
        long_name: technique_params.fetch(:long_name),
        youtube_video_url: technique_params.fetch(:youtube_video_url),
        description: technique_params.fetch(:description),
        topic: technique_params.fetch(:topic).to_i,
      )

      if @technique.save
        redirect_to admin_techniques_path
      else
        render :new
      end
    end

    def edit
      @technique = Technique.find(params[:id])
    end

    def update
      @technique = Technique.find(params[:id])

      if @technique.update(technique_params)
        redirect_to admin_techniques_path
      else
        render :edit
      end
    end

    private

    def technique_params
      params.require(:technique).permit(
        :belt_id,
        :name,
        :long_name,
        :topic,
        :description,
        :youtube_video_url,
      )
    end
  end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  def index
    @belt = Belt.find(params[:belt_id])

    respond_to do |format|
      format.js {}
    end
  end

  def show
    @technique = Technique.find(params[:id])
  end
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/views/admin/techniques/_form.html.erb
<%= simple_form_for [:admin, technique] do |f| %>
  <div class="form-group">
    <%= f.input :name, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.input :long_name, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.input :description, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.input :youtube_video_url, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.association :belt, label_method: :color, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.input :topic, collection: Technique.topics.map { |topic_name, _| [topic_name.humanize, topic_name] }, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/techniques/edit.html.erb
<%= render partial: "form", locals: { technique: @technique } %>

app/views/admin/techniques/index.html.erb
<div>
  <%= link_to "Tilføj ny teknik", new_admin_technique_path, class: "btn btn-default right" %>

	<div class="search col-md-4 right">
  	<%= form_tag admin_techniques_path, method: :get do %>
	  <div class="input-group">
    		<%= search_field_tag :query, params[:query], placeholder: "Søg...", class: "form-control" %>
	      <span class="input-group-btn">
	        <!-- <button class="btn btn-secondary" type="button">Love it</button> -->
		    	<%= button_tag 'Go', class: "btn btn-default" %>
	      </span>
	    </div>
	<% end %>
	</div>
	
	

  <h1>Teknik register</h1>
</div>

<% @belts.each do |belt| %>
  <% next if belt.techniques.where(id: @matching_techniques).empty? %>

  <div class="technique-list">
    <h2>
      <%= belt.color.titleize %>
      (<%= belt.degree %>)
      <span class="right"><i class="fa fa-chevron-up" aria-hidden="true"></i></span>
    </h2>

    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Navn</th>
            <th>Langt navn</th>
            <th>Beskrivelse</th>
            <th>Emne</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% belt.techniques.where(id: @matching_techniques).order(:topic, :name).each do |technique| %>
            <tr>
              <td><%= link_to technique.name.titleize, [technique.belt, technique] %></td>
              <td><%= technique.long_name.titleize %></td>
              <td><%= simple_format technique.description %></td>
              <td><%= technique.topic.titleize %></td>
              <td>
                <%= link_to "Redigere", edit_admin_technique_path(technique), class: "btn btn-xs btn-info" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
<% end %>

app/views/admin/techniques/new.html.erb
<%= simple_form_for [:admin, @technique] do |f| %>
  <div class="form-group">
    <%= f.input :name, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.input :description %>
  </div>

  <div class="form-group">
    <%= f.association :belt, label_method: :color %>
  </div>

  <div class="form-group">
    <%= f.input :topic, collection: Technique.topics %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>