config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  get "/me", to: "me#index", as: :me

  resources :users, only: [:show, :create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root to: "welcome#index"

  resources :belts, only: [] do
    resources :techniques, only: [:index, :show] do
      resources :notes, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      patch :give_user_next_belt
    end

    resources :techniques, only: [:index, :new, :create, :edit, :update]

    resources :belt_applications, only: [:index, :destroy] do
      member do
        post :approve
      end
    end
  end

  resources :belt_applications, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :first_name, :last_name, :email, presence: true

  has_and_belongs_to_many :belts
  has_many :notes
  has_one :belt_application

  after_create :give_white_belt

  enum genders: {
    male: 0,
    female: 1,
  }

  def name
    [first_name, last_name].join(" ")
  end

  def has_belt?(belt)
    belts.include? belt
  end

  def current_belt
    belts.sort_by_kup.last
  end

  def next_belt
    next_belt_index = Belt.sort_by_kup.index(current_belt) + 1
    Belt.sort_by_kup[next_belt_index]
  end

  def give_next_belt
    return if next_belt.nil?
    self.belts << next_belt
  end

  private

  def give_white_belt
    return unless belts.empty?
    self.belts << Belt.sort_by_kup.first
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    def index
      @users = User.all
    end

    def give_user_next_belt
      user = User.find params[:user_id]
      user.give_next_belt

      redirect_to admin_users_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  private

  def user_params
    params[Clearance.configuration.user_parameter].permit(
      :email,
      :password,
      :first_name,
      :last_name,
      :gender,
      :birthdate,
    )
  end
end

app/views/admin/users/index.html.erb
<h1>Medlemmer</h1>

<% if @users.present? %>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Email</th>
        <th>Fornavn</th>
        <th>Efternavn</th>
        <th>Fødselsdato</th>
        <th>Køn</th>
        <th>Bælte</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>

          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.birthdate.to_s(:long) %></td>
          <td>
						<% if user.gender == 1%>
          		Kvinde
						<% else %>
            	Mand
          	<% end %>
					</td>
					<td>
          	<% if user.belts.present? %>
            	<%= user.current_belt.color %>
          	<% else %>
            	Ingen bælte
          	<% end %>
					</td>

          <td>
            <%= button_to "Rediger bælte", admin_user_give_user_next_belt_path(user), method: :patch, class: "btn btn-xs btn-info" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% else %>
  <p>Der er ingen brugere endnu :(</p>
<% end %>