config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  get "/me", to: "me#index", as: :me

  resources :users, only: [:show, :create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root to: "welcome#index"

  resources :belts, only: [] do
    resources :techniques, only: [:index, :show] do
      resources :notes, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      patch :give_user_next_belt
    end

    resources :techniques, only: [:index, :new, :create, :edit, :update]

    resources :belt_applications, only: [:index, :destroy] do
      member do
        post :approve
      end
    end
  end

  resources :belt_applications, only: [:new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gisul</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
  </head>

  <body>

<div class="page-wrap">

    <div id="flash">
      <% flash.each do |key, value| %>	
        <div class="flash <%= key %> alert alert-danger alert-dismissible">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<%= value %>
				</div>
      <% end %>
    </div>

    <div class="title float-block">
      <a href="/" class="logo left">기술</a>
    </div>


    <div class="container">
      <%= yield %>
    </div>

</div>

    <nav class="">
			<div class="col-md-4 col-sm-6 col-xs-12">
      <%= image_tag("shinsonhapkido_logo.png") %>
      <span>Shinson Hapkido - Pensum</span>
			</div>

      <% if current_user.try(:admin?) %>
        <div class="admin-nav col-md-4 col-sm-6 col-xs-12">
          <%= link_to "Brugere", admin_users_path %> |
          <%= link_to "Teknikker", admin_techniques_path %> |
          <%= link_to "Ansøgningerne", admin_belt_applications_path %>
				</div>
      <% end %>
			<div class="user-nav col-md-4 col-sm-12 col-xs-12">
        <% if signed_in? %>
          <p>Annyeong Haseyo, <%= link_to current_user.first_name, me_path %>
						<%= button_to 'Log ud', sign_out_path, method: :delete, class: 'btn btn-xs' %>
          </p>
        <% else %>
				<div class="sign-log-links">
          <%= link_to 'Log ind', sign_in_path %> |
          <%= link_to 'Sign up', sign_up_path %>
				</div>
        <% end %>
      </div>
    </nav>

  </body>
</html>